name: simple_in_app_webview
description: The most simple to implement in app web view package
version: 0.1.7
homepage: https://github.com/johnmelodyme/simple_in_app_webview.git

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: any
  url_launcher: ^6.0.9
  flutter_share: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
